# Generated by Django 4.1.4 on 2022-12-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('unique_code', models.CharField(max_length=10, unique=True)),
                ('size', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=10)),
                ('quality', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_img/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.productmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('Black', 'black')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.productmainmodel')),
            ],
        ),
    ]
